#!/usr/bin/python

import os
# import sys

if os.getuid() != 0:
    print("Must be root")
    exit(1)

# os.chdir('/etc')
# print(os.path.realpath(os.path.curdir))
try:
    os.remove(os.path.join('/etc', 'environment'))
except OSError as error:
    print(error)

os.system('ln -s /etc/environment.proxybypass /etc/environment')

