#!/usr/bin/python

import os
import sys

if os.getuid() != 0:
    print("Must be root")
    exit(1)

if len(sys.argv) !=2:
    print('setproxy expects exactly one comand-line argument')
    exit(1)

options = ['noproxy', 'proxy', 'proxybypass']
# get possible configurations from /etc/environment.*
if sys.argv[1] not in options:
    print('setproxy expects only valid options')
    print(options)
    exit(1)



# os.chdir('/etc')
# print(os.path.realpath(os.path.curdir))
try:
    os.remove(os.path.join('/etc', 'environment'))
except OSError as error:
    print(error)

os.system('ln -s /etc/environment.%s /etc/environment' % sys.argv[1])
